name: Bygg og deploy planlegger redirect
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'server_for_redirect/**'
      - '.github/workflows/build-redirect.yml'
      - '.deploy/planlegger_redirect.yaml'
env:
  APP_NAME: fp-planlegger-redirect

jobs:
  build:
    name: Build
    permissions:
      contents: read
      id-token: write
    uses: navikt/fp-gha-workflows/.github/workflows/build-docker.yml@main
    with:
      push-image: ${{ github.ref_name == 'master' }}
      docker_context: ./server_for_redirect
      app_name: /${{env.APP_NAME}}
    secrets: inherit

  promote-prod:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main # ratchet:exclude
    with:
      gar: true
      image: ${{ needs.build.outputs.build-version }}
      cluster: prod-gcp
      app: /${{env.APP_NAME}}
      naiserator_file: planlegger_redirect.yaml
    secrets: inherit
