name: Bygg og deploy planlegger redirect
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'server_for_redirect/**'
      - '.github/workflows/build-redirect.yml'
      - '.deploy/planlegger_redirect.yaml'
env:
  APP_NAME: fp-planlegger-redirect

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      build-version: ${{ steps.generate-build-version.outputs.build-version }}
    steps:
      - name: Bygg og push docker image
        uses: navikt/fp-gha-workflows/.github/workflows/build-docker@main # ratchet:exclude
        with:
          build-version: ${{ steps.generate-build-version.outputs.build-version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-image: ${{ github.ref_name == 'master' }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          docker_context: ./server_for_redirect
          app_name: /${{env.APP_NAME}}

  promote-prod:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
    steps:
      - uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main # ratchet:exclude
        with:
          gar: true
          image: ${{ needs.build.outputs.build-version }}
          cluster: prod-gcp
          app: /${{env.APP_NAME}}
          naiserator_file: planlegger_redirect.yaml
